WIDTH = window.innerWidth * 0.99;
HEIGHT = window.innerHeight * 0.92;
ROW_WIDTH = 50;
COL_WIDTH = 50;

// GRID variable will receive all cells in the grid
GRID = [];
STACK = [];
GROWING_TREE_ARRAY = [];
ACTIVE = [];
SIDEWINDERS_RUN = [];
CURRENT_CELL = new Cell();

//GLOBALS for algorithm switching
ALGORITHM_TRIGGER = "";

// BINARY_TREE_BUTTON = 0;
// SIDEWINDER_BUTTON = 0;
// ALDOUS_BRODER_BUTTON = 0;
// WILSONS_BUTTON = 0;
// HUNT_AND_KILL_BUTTON = 0;
// RECURSIVE_BACKTRACKER_BUTTON = 0;
// ELLERS_BUTTON = 0;
// GROWING_TREE_BUTTON = 0;
// SIMPLIFIED_PRIMS_BUTTON = 0;
// TRUE_PRIMS_BUTTON = 0;
// KRUSKALS_BUTTON = 0;
// BLOB_BUTTON = 0;
// WEAVE_BUTTON = 0;